[2025-05-14T05:23:07.133+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Sales_Performance_ETL.Extract_Data manual__2025-05-14T05:23:06.342504+00:00 [queued]>
[2025-05-14T05:23:07.145+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Sales_Performance_ETL.Extract_Data manual__2025-05-14T05:23:06.342504+00:00 [queued]>
[2025-05-14T05:23:07.146+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-05-14T05:23:07.147+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2025-05-14T05:23:07.147+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-05-14T05:23:07.164+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): Extract_Data> on 2025-05-14 05:23:06.342504+00:00
[2025-05-14T05:23:07.169+0000] {standard_task_runner.py:52} INFO - Started process 293 to run task
[2025-05-14T05:23:07.177+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Sales_Performance_ETL', 'Extract_Data', 'manual__2025-05-14T05:23:06.342504+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_Hisham_Audiputra_Suharto_DAG.py', '--cfg-path', '/tmp/tmp19bfjq81', '--error-file', '/tmp/tmpep1cubdd']
[2025-05-14T05:23:07.179+0000] {standard_task_runner.py:80} INFO - Job 2: Subtask Extract_Data
[2025-05-14T05:23:07.275+0000] {task_command.py:371} INFO - Running <TaskInstance: Sales_Performance_ETL.Extract_Data manual__2025-05-14T05:23:06.342504+00:00 [running]> on host 158346e7cc01
[2025-05-14T05:23:07.356+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Hisham
AIRFLOW_CTX_DAG_ID=Sales_Performance_ETL
AIRFLOW_CTX_TASK_ID=Extract_Data
AIRFLOW_CTX_EXECUTION_DATE=2025-05-14T05:23:06.342504+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-14T05:23:06.342504+00:00
[2025-05-14T05:23:07.358+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-05-14T05:23:07.359+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'sudo -u *** python /opt/***/scripts/Extract_Data.py']
[2025-05-14T05:23:07.370+0000] {subprocess.py:85} INFO - Output:
[2025-05-14T05:23:07.456+0000] {subprocess.py:92} INFO - Traceback (most recent call last):
[2025-05-14T05:23:07.457+0000] {subprocess.py:92} INFO -   File "/opt/***/scripts/Extract_Data.py", line 1, in <module>
[2025-05-14T05:23:07.458+0000] {subprocess.py:92} INFO -     import kagglehub
[2025-05-14T05:23:07.459+0000] {subprocess.py:92} INFO - ModuleNotFoundError: No module named 'kagglehub'
[2025-05-14T05:23:07.461+0000] {subprocess.py:96} INFO - Command exited with return code 1
[2025-05-14T05:23:07.483+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-14T05:23:07.490+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=Sales_Performance_ETL, task_id=Extract_Data, execution_date=20250514T052306, start_date=20250514T052307, end_date=20250514T052307
[2025-05-14T05:23:07.502+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 2 for task Extract_Data (Bash command failed. The command returned a non-zero exit code 1.; 293)
[2025-05-14T05:23:07.549+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-05-14T05:23:07.606+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
