[2025-05-20T14:48:32.739+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Scheduler_Traffict_Accident.Load_Data scheduled__2025-05-20T14:30:00+00:00 [queued]>
[2025-05-20T14:48:32.752+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Scheduler_Traffict_Accident.Load_Data scheduled__2025-05-20T14:30:00+00:00 [queued]>
[2025-05-20T14:48:32.753+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-05-20T14:48:32.755+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2025-05-20T14:48:32.757+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-05-20T14:48:32.772+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): Load_Data> on 2025-05-20 14:30:00+00:00
[2025-05-20T14:48:32.777+0000] {standard_task_runner.py:52} INFO - Started process 940 to run task
[2025-05-20T14:48:32.780+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Scheduler_Traffict_Accident', 'Load_Data', 'scheduled__2025-05-20T14:30:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/Scheduler_Traffict_Accident.py', '--cfg-path', '/tmp/tmp5wk6uasn', '--error-file', '/tmp/tmpsdyw74_7']
[2025-05-20T14:48:32.782+0000] {standard_task_runner.py:80} INFO - Job 5: Subtask Load_Data
[2025-05-20T14:48:32.849+0000] {task_command.py:371} INFO - Running <TaskInstance: Scheduler_Traffict_Accident.Load_Data scheduled__2025-05-20T14:30:00+00:00 [running]> on host 240265f9b255
[2025-05-20T14:48:32.925+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Hisham
AIRFLOW_CTX_DAG_ID=Scheduler_Traffict_Accident
AIRFLOW_CTX_TASK_ID=Load_Data
AIRFLOW_CTX_EXECUTION_DATE=2025-05-20T14:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-05-20T14:30:00+00:00
[2025-05-20T14:48:32.927+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-05-20T14:48:32.929+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'sudo -u *** python /opt/***/scripts/Load_Data.py']
[2025-05-20T14:48:32.939+0000] {subprocess.py:85} INFO - Output:
[2025-05-20T14:48:34.327+0000] {subprocess.py:92} INFO - WARNING: An illegal reflective access operation has occurred
[2025-05-20T14:48:34.328+0000] {subprocess.py:92} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.7/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2025-05-20T14:48:34.329+0000] {subprocess.py:92} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2025-05-20T14:48:34.330+0000] {subprocess.py:92} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2025-05-20T14:48:34.330+0000] {subprocess.py:92} INFO - WARNING: All illegal access operations will be denied in a future release
[2025-05-20T14:48:34.457+0000] {subprocess.py:92} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.7/site-packages/pyspark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-05-20T14:48:34.521+0000] {subprocess.py:92} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-05-20T14:48:34.522+0000] {subprocess.py:92} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-05-20T14:48:34.526+0000] {subprocess.py:92} INFO - org.postgresql#postgresql added as a dependency
[2025-05-20T14:48:34.527+0000] {subprocess.py:92} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-fee300e7-7a94-49bf-9221-9a5b2f78da3d;1.0
[2025-05-20T14:48:34.528+0000] {subprocess.py:92} INFO - 	confs: [default]
[2025-05-20T14:48:34.608+0000] {subprocess.py:92} INFO - 	found org.postgresql#postgresql;42.6.0 in central
[2025-05-20T14:48:34.628+0000] {subprocess.py:92} INFO - 	found org.checkerframework#checker-qual;3.31.0 in central
[2025-05-20T14:48:34.639+0000] {subprocess.py:92} INFO - :: resolution report :: resolve 109ms :: artifacts dl 3ms
[2025-05-20T14:48:34.640+0000] {subprocess.py:92} INFO - 	:: modules in use:
[2025-05-20T14:48:34.641+0000] {subprocess.py:92} INFO - 	org.checkerframework#checker-qual;3.31.0 from central in [default]
[2025-05-20T14:48:34.642+0000] {subprocess.py:92} INFO - 	org.postgresql#postgresql;42.6.0 from central in [default]
[2025-05-20T14:48:34.642+0000] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-05-20T14:48:34.643+0000] {subprocess.py:92} INFO - 	|                  |            modules            ||   artifacts   |
[2025-05-20T14:48:34.643+0000] {subprocess.py:92} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-05-20T14:48:34.644+0000] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-05-20T14:48:34.644+0000] {subprocess.py:92} INFO - 	|      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
[2025-05-20T14:48:34.645+0000] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-05-20T14:48:34.646+0000] {subprocess.py:92} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-fee300e7-7a94-49bf-9221-9a5b2f78da3d
[2025-05-20T14:48:34.646+0000] {subprocess.py:92} INFO - 	confs: [default]
[2025-05-20T14:48:34.648+0000] {subprocess.py:92} INFO - 	0 artifacts copied, 2 already retrieved (0kB/4ms)
[2025-05-20T14:48:34.809+0000] {subprocess.py:92} INFO - 25/05/20 14:48:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-20T14:48:35.034+0000] {subprocess.py:92} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2025-05-20T14:48:35.035+0000] {subprocess.py:92} INFO - Setting default log level to "WARN".
[2025-05-20T14:48:35.035+0000] {subprocess.py:92} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-05-20T14:48:43.576+0000] {subprocess.py:92} INFO - [Stage 6:>                                                          (0 + 1) / 1]25/05/20 14:48:43 ERROR Executor: Exception in task 0.0 in stage 6.0 (TID 15)
[2025-05-20T14:48:43.578+0000] {subprocess.py:92} INFO - java.sql.BatchUpdateException: Batch entry 0 INSERT INTO date ("crash_date","crash_year","crash_month","crash_day_of_week","crash_week") VALUES ('2013-03-01',2013,3,6,1) was aborted: ERROR: column "crash_date" is of type date but expression is of type character varying
[2025-05-20T14:48:43.580+0000] {subprocess.py:92} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-20T14:48:43.581+0000] {subprocess.py:92} INFO -   Position: 101  Call getNextException to see other errors in the batch.
[2025-05-20T14:48:43.582+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
[2025-05-20T14:48:43.583+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:880)
[2025-05-20T14:48:43.584+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
[2025-05-20T14:48:43.585+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1685)
[2025-05-20T14:48:43.587+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:687)
[2025-05-20T14:48:43.587+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:856)
[2025-05-20T14:48:43.588+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:854)
[2025-05-20T14:48:43.589+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
[2025-05-20T14:48:43.590+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
[2025-05-20T14:48:43.591+0000] {subprocess.py:92} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
[2025-05-20T14:48:43.592+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2025-05-20T14:48:43.593+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2025-05-20T14:48:43.594+0000] {subprocess.py:92} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2025-05-20T14:48:43.594+0000] {subprocess.py:92} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2025-05-20T14:48:43.595+0000] {subprocess.py:92} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2025-05-20T14:48:43.596+0000] {subprocess.py:92} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-05-20T14:48:43.596+0000] {subprocess.py:92} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-05-20T14:48:43.597+0000] {subprocess.py:92} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-20T14:48:43.598+0000] {subprocess.py:92} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: column "crash_date" is of type date but expression is of type character varying
[2025-05-20T14:48:43.598+0000] {subprocess.py:92} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-20T14:48:43.599+0000] {subprocess.py:92} INFO -   Position: 101
[2025-05-20T14:48:43.600+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
[2025-05-20T14:48:43.600+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
[2025-05-20T14:48:43.601+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
[2025-05-20T14:48:43.602+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:327)
[2025-05-20T14:48:43.602+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:877)
[2025-05-20T14:48:43.603+0000] {subprocess.py:92} INFO - 	... 16 more
[2025-05-20T14:48:43.615+0000] {subprocess.py:92} INFO - 25/05/20 14:48:43 WARN TaskSetManager: Lost task 0.0 in stage 6.0 (TID 15) (240265f9b255 executor driver): java.sql.BatchUpdateException: Batch entry 0 INSERT INTO date ("crash_date","crash_year","crash_month","crash_day_of_week","crash_week") VALUES ('2013-03-01',2013,3,6,1) was aborted: ERROR: column "crash_date" is of type date but expression is of type character varying
[2025-05-20T14:48:43.616+0000] {subprocess.py:92} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-20T14:48:43.616+0000] {subprocess.py:92} INFO -   Position: 101  Call getNextException to see other errors in the batch.
[2025-05-20T14:48:43.617+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
[2025-05-20T14:48:43.617+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:880)
[2025-05-20T14:48:43.618+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
[2025-05-20T14:48:43.618+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1685)
[2025-05-20T14:48:43.619+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:687)
[2025-05-20T14:48:43.620+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:856)
[2025-05-20T14:48:43.620+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:854)
[2025-05-20T14:48:43.622+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
[2025-05-20T14:48:43.622+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
[2025-05-20T14:48:43.623+0000] {subprocess.py:92} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
[2025-05-20T14:48:43.623+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2025-05-20T14:48:43.624+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2025-05-20T14:48:43.624+0000] {subprocess.py:92} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2025-05-20T14:48:43.624+0000] {subprocess.py:92} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2025-05-20T14:48:43.625+0000] {subprocess.py:92} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2025-05-20T14:48:43.625+0000] {subprocess.py:92} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-05-20T14:48:43.625+0000] {subprocess.py:92} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-05-20T14:48:43.626+0000] {subprocess.py:92} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-20T14:48:43.626+0000] {subprocess.py:92} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: column "crash_date" is of type date but expression is of type character varying
[2025-05-20T14:48:43.626+0000] {subprocess.py:92} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-20T14:48:43.627+0000] {subprocess.py:92} INFO -   Position: 101
[2025-05-20T14:48:43.627+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
[2025-05-20T14:48:43.627+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
[2025-05-20T14:48:43.628+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
[2025-05-20T14:48:43.628+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:327)
[2025-05-20T14:48:43.629+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:877)
[2025-05-20T14:48:43.630+0000] {subprocess.py:92} INFO - 	... 16 more
[2025-05-20T14:48:43.630+0000] {subprocess.py:92} INFO - 
[2025-05-20T14:48:43.631+0000] {subprocess.py:92} INFO - 25/05/20 14:48:43 ERROR TaskSetManager: Task 0 in stage 6.0 failed 1 times; aborting job
[2025-05-20T14:48:43.765+0000] {subprocess.py:92} INFO - Traceback (most recent call last):
[2025-05-20T14:48:43.766+0000] {subprocess.py:92} INFO -   File "/opt/***/scripts/Load_Data.py", line 21, in <module>
[2025-05-20T14:48:43.767+0000] {subprocess.py:92} INFO -     data_date.write.jdbc(url=postgres_url, table="date", mode="append", properties=postgres_properties)
[2025-05-20T14:48:43.767+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/sql/readwriter.py", line 1445, in jdbc
[2025-05-20T14:48:43.768+0000] {subprocess.py:92} INFO -     self.mode(mode)._jwrite.jdbc(url, table, jprop)
[2025-05-20T14:48:43.768+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1305, in __call__
[2025-05-20T14:48:43.769+0000] {subprocess.py:92} INFO -     answer, self.gateway_client, self.target_id, self.name)
[2025-05-20T14:48:43.769+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/sql/utils.py", line 111, in deco
[2025-05-20T14:48:43.770+0000] {subprocess.py:92} INFO -     return f(*a, **kw)
[2025-05-20T14:48:43.770+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
[2025-05-20T14:48:43.770+0000] {subprocess.py:92} INFO -     format(target_id, ".", name), value)
[2025-05-20T14:48:43.771+0000] {subprocess.py:92} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o53.jdbc.
[2025-05-20T14:48:43.771+0000] {subprocess.py:92} INFO - : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 6.0 failed 1 times, most recent failure: Lost task 0.0 in stage 6.0 (TID 15) (240265f9b255 executor driver): java.sql.BatchUpdateException: Batch entry 0 INSERT INTO date ("crash_date","crash_year","crash_month","crash_day_of_week","crash_week") VALUES ('2013-03-01',2013,3,6,1) was aborted: ERROR: column "crash_date" is of type date but expression is of type character varying
[2025-05-20T14:48:43.772+0000] {subprocess.py:92} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-20T14:48:43.772+0000] {subprocess.py:92} INFO -   Position: 101  Call getNextException to see other errors in the batch.
[2025-05-20T14:48:43.773+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
[2025-05-20T14:48:43.773+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:880)
[2025-05-20T14:48:43.773+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
[2025-05-20T14:48:43.773+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1685)
[2025-05-20T14:48:43.774+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:687)
[2025-05-20T14:48:43.774+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:856)
[2025-05-20T14:48:43.775+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:854)
[2025-05-20T14:48:43.775+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
[2025-05-20T14:48:43.776+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
[2025-05-20T14:48:43.776+0000] {subprocess.py:92} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
[2025-05-20T14:48:43.776+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2025-05-20T14:48:43.776+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2025-05-20T14:48:43.777+0000] {subprocess.py:92} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2025-05-20T14:48:43.777+0000] {subprocess.py:92} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2025-05-20T14:48:43.777+0000] {subprocess.py:92} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2025-05-20T14:48:43.778+0000] {subprocess.py:92} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-05-20T14:48:43.778+0000] {subprocess.py:92} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-05-20T14:48:43.778+0000] {subprocess.py:92} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-20T14:48:43.779+0000] {subprocess.py:92} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: column "crash_date" is of type date but expression is of type character varying
[2025-05-20T14:48:43.779+0000] {subprocess.py:92} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-20T14:48:43.779+0000] {subprocess.py:92} INFO -   Position: 101
[2025-05-20T14:48:43.780+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
[2025-05-20T14:48:43.781+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
[2025-05-20T14:48:43.781+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
[2025-05-20T14:48:43.782+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:327)
[2025-05-20T14:48:43.782+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:877)
[2025-05-20T14:48:43.783+0000] {subprocess.py:92} INFO - 	... 16 more
[2025-05-20T14:48:43.783+0000] {subprocess.py:92} INFO - 
[2025-05-20T14:48:43.784+0000] {subprocess.py:92} INFO - Driver stacktrace:
[2025-05-20T14:48:43.784+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2258)
[2025-05-20T14:48:43.784+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2207)
[2025-05-20T14:48:43.785+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2206)
[2025-05-20T14:48:43.785+0000] {subprocess.py:92} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-05-20T14:48:43.785+0000] {subprocess.py:92} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-05-20T14:48:43.786+0000] {subprocess.py:92} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-05-20T14:48:43.786+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2206)
[2025-05-20T14:48:43.786+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1079)
[2025-05-20T14:48:43.787+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1079)
[2025-05-20T14:48:43.787+0000] {subprocess.py:92} INFO - 	at scala.Option.foreach(Option.scala:407)
[2025-05-20T14:48:43.787+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1079)
[2025-05-20T14:48:43.788+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2445)
[2025-05-20T14:48:43.788+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2387)
[2025-05-20T14:48:43.788+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2376)
[2025-05-20T14:48:43.789+0000] {subprocess.py:92} INFO - 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2025-05-20T14:48:43.789+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:868)
[2025-05-20T14:48:43.790+0000] {subprocess.py:92} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2196)
[2025-05-20T14:48:43.790+0000] {subprocess.py:92} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2217)
[2025-05-20T14:48:43.790+0000] {subprocess.py:92} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2236)
[2025-05-20T14:48:43.791+0000] {subprocess.py:92} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2261)
[2025-05-20T14:48:43.791+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$1(RDD.scala:1020)
[2025-05-20T14:48:43.792+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2025-05-20T14:48:43.792+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
[2025-05-20T14:48:43.792+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
[2025-05-20T14:48:43.793+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:1018)
[2025-05-20T14:48:43.793+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.saveTable(JdbcUtils.scala:854)
[2025-05-20T14:48:43.793+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:68)
[2025-05-20T14:48:43.794+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
[2025-05-20T14:48:43.794+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
[2025-05-20T14:48:43.794+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
[2025-05-20T14:48:43.795+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:90)
[2025-05-20T14:48:43.796+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
[2025-05-20T14:48:43.797+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
[2025-05-20T14:48:43.798+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2025-05-20T14:48:43.798+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
[2025-05-20T14:48:43.798+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
[2025-05-20T14:48:43.799+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:132)
[2025-05-20T14:48:43.799+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:131)
[2025-05-20T14:48:43.800+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:989)
[2025-05-20T14:48:43.801+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
[2025-05-20T14:48:43.802+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
[2025-05-20T14:48:43.803+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
[2025-05-20T14:48:43.803+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
[2025-05-20T14:48:43.803+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
[2025-05-20T14:48:43.804+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:989)
[2025-05-20T14:48:43.804+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:438)
[2025-05-20T14:48:43.805+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:415)
[2025-05-20T14:48:43.806+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:301)
[2025-05-20T14:48:43.806+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.DataFrameWriter.jdbc(DataFrameWriter.scala:817)
[2025-05-20T14:48:43.807+0000] {subprocess.py:92} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-20T14:48:43.807+0000] {subprocess.py:92} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-20T14:48:43.809+0000] {subprocess.py:92} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-20T14:48:43.810+0000] {subprocess.py:92} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-20T14:48:43.812+0000] {subprocess.py:92} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-20T14:48:43.817+0000] {subprocess.py:92} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-20T14:48:43.821+0000] {subprocess.py:92} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-20T14:48:43.822+0000] {subprocess.py:92} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-20T14:48:43.822+0000] {subprocess.py:92} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-20T14:48:43.823+0000] {subprocess.py:92} INFO - 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
[2025-05-20T14:48:43.824+0000] {subprocess.py:92} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-20T14:48:43.824+0000] {subprocess.py:92} INFO - Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO date ("crash_date","crash_year","crash_month","crash_day_of_week","crash_week") VALUES ('2013-03-01',2013,3,6,1) was aborted: ERROR: column "crash_date" is of type date but expression is of type character varying
[2025-05-20T14:48:43.825+0000] {subprocess.py:92} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-20T14:48:43.825+0000] {subprocess.py:92} INFO -   Position: 101  Call getNextException to see other errors in the batch.
[2025-05-20T14:48:43.826+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
[2025-05-20T14:48:43.827+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:880)
[2025-05-20T14:48:43.828+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
[2025-05-20T14:48:43.828+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1685)
[2025-05-20T14:48:43.829+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:687)
[2025-05-20T14:48:43.832+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:856)
[2025-05-20T14:48:43.832+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:854)
[2025-05-20T14:48:43.833+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
[2025-05-20T14:48:43.833+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
[2025-05-20T14:48:43.834+0000] {subprocess.py:92} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
[2025-05-20T14:48:43.834+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2025-05-20T14:48:43.835+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2025-05-20T14:48:43.836+0000] {subprocess.py:92} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2025-05-20T14:48:43.836+0000] {subprocess.py:92} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2025-05-20T14:48:43.837+0000] {subprocess.py:92} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2025-05-20T14:48:43.838+0000] {subprocess.py:92} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-05-20T14:48:43.839+0000] {subprocess.py:92} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-05-20T14:48:43.839+0000] {subprocess.py:92} INFO - 	... 1 more
[2025-05-20T14:48:43.840+0000] {subprocess.py:92} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: column "crash_date" is of type date but expression is of type character varying
[2025-05-20T14:48:43.841+0000] {subprocess.py:92} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-20T14:48:43.842+0000] {subprocess.py:92} INFO -   Position: 101
[2025-05-20T14:48:43.842+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
[2025-05-20T14:48:43.843+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
[2025-05-20T14:48:43.844+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
[2025-05-20T14:48:43.844+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:327)
[2025-05-20T14:48:43.845+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:877)
[2025-05-20T14:48:43.846+0000] {subprocess.py:92} INFO - 	... 16 more
[2025-05-20T14:48:43.846+0000] {subprocess.py:92} INFO - 
[2025-05-20T14:48:44.219+0000] {subprocess.py:96} INFO - Command exited with return code 1
[2025-05-20T14:48:44.248+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-20T14:48:44.263+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=Scheduler_Traffict_Accident, task_id=Load_Data, execution_date=20250520T143000, start_date=20250520T144832, end_date=20250520T144844
[2025-05-20T14:48:44.285+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 5 for task Load_Data (Bash command failed. The command returned a non-zero exit code 1.; 940)
[2025-05-20T14:48:44.310+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-05-20T14:48:44.357+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
