[2025-05-22T16:18:48.385+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Datamart_Traffict_Accident.Extract_Datamart_Data manual__2025-05-22T16:18:47.324119+00:00 [queued]>
[2025-05-22T16:18:48.395+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Datamart_Traffict_Accident.Extract_Datamart_Data manual__2025-05-22T16:18:47.324119+00:00 [queued]>
[2025-05-22T16:18:48.396+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-22T16:18:48.410+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): Extract_Datamart_Data> on 2025-05-22 16:18:47.324119+00:00
[2025-05-22T16:18:48.415+0000] {standard_task_runner.py:57} INFO - Started process 254 to run task
[2025-05-22T16:18:48.419+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Datamart_Traffict_Accident', 'Extract_Datamart_Data', 'manual__2025-05-22T16:18:47.324119+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/Datamart_Traffict_Accident.py', '--cfg-path', '/tmp/tmp4syw7h6r']
[2025-05-22T16:18:48.423+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask Extract_Datamart_Data
[2025-05-22T16:18:48.483+0000] {task_command.py:416} INFO - Running <TaskInstance: Datamart_Traffict_Accident.Extract_Datamart_Data manual__2025-05-22T16:18:47.324119+00:00 [running]> on host 37de2a8083a6
[2025-05-22T16:18:48.565+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Hisham' AIRFLOW_CTX_DAG_ID='Datamart_Traffict_Accident' AIRFLOW_CTX_TASK_ID='Extract_Datamart_Data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T16:18:47.324119+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-22T16:18:47.324119+00:00'
[2025-05-22T16:18:48.567+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-22T16:18:48.568+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sudo -u *** python /opt/***/scripts/Extract_Datamart_Data.py']
[2025-05-22T16:18:48.578+0000] {subprocess.py:86} INFO - Output:
[2025-05-22T16:18:50.467+0000] {subprocess.py:93} INFO - WARNING: An illegal reflective access operation has occurred
[2025-05-22T16:18:50.468+0000] {subprocess.py:93} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2025-05-22T16:18:50.469+0000] {subprocess.py:93} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2025-05-22T16:18:50.469+0000] {subprocess.py:93} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2025-05-22T16:18:50.469+0000] {subprocess.py:93} INFO - WARNING: All illegal access operations will be denied in a future release
[2025-05-22T16:18:50.628+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-05-22T16:18:50.709+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-05-22T16:18:50.710+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-05-22T16:18:50.714+0000] {subprocess.py:93} INFO - org.postgresql#postgresql added as a dependency
[2025-05-22T16:18:50.715+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-0d93c110-d3bb-43c9-b639-b6ab778662cf;1.0
[2025-05-22T16:18:50.716+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-22T16:18:53.301+0000] {subprocess.py:93} INFO - 	found org.postgresql#postgresql;42.6.0 in central
[2025-05-22T16:18:54.571+0000] {subprocess.py:93} INFO - 	found org.checkerframework#checker-qual;3.31.0 in central
[2025-05-22T16:18:54.579+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/postgresql/postgresql/42.6.0/postgresql-42.6.0.jar ...
[2025-05-22T16:18:56.003+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.postgresql#postgresql;42.6.0!postgresql.jar (1425ms)
[2025-05-22T16:18:56.006+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/checkerframework/checker-qual/3.31.0/checker-qual-3.31.0.jar ...
[2025-05-22T16:18:56.264+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.checkerframework#checker-qual;3.31.0!checker-qual.jar (260ms)
[2025-05-22T16:18:56.266+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 3862ms :: artifacts dl 1688ms
[2025-05-22T16:18:56.267+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-05-22T16:18:56.268+0000] {subprocess.py:93} INFO - 	org.checkerframework#checker-qual;3.31.0 from central in [default]
[2025-05-22T16:18:56.269+0000] {subprocess.py:93} INFO - 	org.postgresql#postgresql;42.6.0 from central in [default]
[2025-05-22T16:18:56.269+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T16:18:56.270+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-05-22T16:18:56.271+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-05-22T16:18:56.272+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T16:18:56.272+0000] {subprocess.py:93} INFO - 	|      default     |   2   |   2   |   2   |   0   ||   2   |   2   |
[2025-05-22T16:18:56.273+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T16:18:56.273+0000] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-0d93c110-d3bb-43c9-b639-b6ab778662cf
[2025-05-22T16:18:56.274+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-22T16:18:56.282+0000] {subprocess.py:93} INFO - 	2 artifacts copied, 0 already retrieved (1274kB/9ms)
[2025-05-22T16:18:56.466+0000] {subprocess.py:93} INFO - 25/05/22 16:18:56 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-22T16:18:56.734+0000] {subprocess.py:93} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2025-05-22T16:18:56.735+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2025-05-22T16:18:56.736+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-05-22T16:18:59.308+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-22T16:18:59.309+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/Extract_Datamart_Data.py", line 19, in <module>
[2025-05-22T16:18:59.319+0000] {subprocess.py:93} INFO -     data_Date = spark.read.jdbc(url=postgres_url, table="date", properties=postgres_properties)
[2025-05-22T16:18:59.320+0000] {subprocess.py:93} INFO -                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-05-22T16:18:59.320+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/sql/readwriter.py", line 871, in jdbc
[2025-05-22T16:18:59.321+0000] {subprocess.py:93} INFO -     return self._df(self._jreader.jdbc(url, table, jprop))
[2025-05-22T16:18:59.321+0000] {subprocess.py:93} INFO -                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-05-22T16:18:59.321+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/py4j/java_gateway.py", line 1304, in __call__
[2025-05-22T16:18:59.322+0000] {subprocess.py:93} INFO -     return_value = get_return_value(
[2025-05-22T16:18:59.323+0000] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^
[2025-05-22T16:18:59.323+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/sql/utils.py", line 111, in deco
[2025-05-22T16:18:59.324+0000] {subprocess.py:93} INFO -     return f(*a, **kw)
[2025-05-22T16:18:59.324+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^
[2025-05-22T16:18:59.324+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/py4j/protocol.py", line 326, in get_return_value
[2025-05-22T16:18:59.325+0000] {subprocess.py:93} INFO -     raise Py4JJavaError(
[2025-05-22T16:18:59.325+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o33.jdbc.
[2025-05-22T16:18:59.326+0000] {subprocess.py:93} INFO - : java.lang.NoClassDefFoundError: org/postgresql/hostchooser/HostRequirement
[2025-05-22T16:18:59.327+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:220)
[2025-05-22T16:18:59.327+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
[2025-05-22T16:18:59.328+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
[2025-05-22T16:18:59.328+0000] {subprocess.py:93} INFO - 	at org.postgresql.Driver.makeConnection(Driver.java:443)
[2025-05-22T16:18:59.329+0000] {subprocess.py:93} INFO - 	at org.postgresql.Driver.connect(Driver.java:297)
[2025-05-22T16:18:59.329+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.connection.BasicConnectionProvider.getConnection(BasicConnectionProvider.scala:49)
[2025-05-22T16:18:59.330+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.connection.ConnectionProvider$.create(ConnectionProvider.scala:68)
[2025-05-22T16:18:59.330+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$createConnectionFactory$1(JdbcUtils.scala:62)
[2025-05-22T16:18:59.331+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD$.resolveTable(JDBCRDD.scala:56)
[2025-05-22T16:18:59.331+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRelation$.getSchema(JDBCRelation.scala:226)
[2025-05-22T16:18:59.332+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:35)
[2025-05-22T16:18:59.332+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:355)
[2025-05-22T16:18:59.333+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:325)
[2025-05-22T16:18:59.333+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:307)
[2025-05-22T16:18:59.334+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-22T16:18:59.335+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:307)
[2025-05-22T16:18:59.335+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:225)
[2025-05-22T16:18:59.335+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.jdbc(DataFrameReader.scala:340)
[2025-05-22T16:18:59.336+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-22T16:18:59.337+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-22T16:18:59.337+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-22T16:18:59.338+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-22T16:18:59.339+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-22T16:18:59.339+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-22T16:18:59.340+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-22T16:18:59.341+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-22T16:18:59.341+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-22T16:18:59.342+0000] {subprocess.py:93} INFO - 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
[2025-05-22T16:18:59.343+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-22T16:18:59.344+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: org.postgresql.hostchooser.HostRequirement
[2025-05-22T16:18:59.345+0000] {subprocess.py:93} INFO - 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:460)
[2025-05-22T16:18:59.346+0000] {subprocess.py:93} INFO - 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
[2025-05-22T16:18:59.346+0000] {subprocess.py:93} INFO - 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[2025-05-22T16:18:59.347+0000] {subprocess.py:93} INFO - 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
[2025-05-22T16:18:59.348+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
[2025-05-22T16:18:59.349+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
[2025-05-22T16:18:59.349+0000] {subprocess.py:93} INFO - 	... 29 more
[2025-05-22T16:18:59.350+0000] {subprocess.py:93} INFO - Caused by: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
[2025-05-22T16:18:59.350+0000] {subprocess.py:93} INFO - 	at java.base/java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:1019)
[2025-05-22T16:18:59.351+0000] {subprocess.py:93} INFO - 	at java.base/java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:1029)
[2025-05-22T16:18:59.351+0000] {subprocess.py:93} INFO - 	at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:479)
[2025-05-22T16:18:59.352+0000] {subprocess.py:93} INFO - 	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
[2025-05-22T16:18:59.352+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.loader.Resource.getBytes(Resource.java:124)
[2025-05-22T16:18:59.353+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getBytes(URLClassPath.java:884)
[2025-05-22T16:18:59.353+0000] {subprocess.py:93} INFO - 	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
[2025-05-22T16:18:59.354+0000] {subprocess.py:93} INFO - 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
[2025-05-22T16:18:59.354+0000] {subprocess.py:93} INFO - 	... 34 more
[2025-05-22T16:18:59.355+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:59.786+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-22T16:18:59.814+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-22T16:18:59.822+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Datamart_Traffict_Accident, task_id=Extract_Datamart_Data, execution_date=20250522T161847, start_date=20250522T161848, end_date=20250522T161859
[2025-05-22T16:18:59.856+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2 for task Extract_Datamart_Data (Bash command failed. The command returned a non-zero exit code 1.; 254)
[2025-05-22T16:18:59.872+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-22T16:18:59.909+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
