[2025-05-22T16:15:10.327+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Scheduler_Traffict_Accident.Transform_Data scheduled__2025-05-22T16:00:00+00:00 [queued]>
[2025-05-22T16:15:10.338+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Scheduler_Traffict_Accident.Transform_Data scheduled__2025-05-22T16:00:00+00:00 [queued]>
[2025-05-22T16:15:10.339+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-22T16:15:10.355+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): Transform_Data> on 2025-05-22 16:00:00+00:00
[2025-05-22T16:15:10.363+0000] {standard_task_runner.py:57} INFO - Started process 3777 to run task
[2025-05-22T16:15:10.366+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Scheduler_Traffict_Accident', 'Transform_Data', 'scheduled__2025-05-22T16:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/Scheduler_Traffict_Accident.py', '--cfg-path', '/tmp/tmpkkf9li61']
[2025-05-22T16:15:10.369+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask Transform_Data
[2025-05-22T16:15:10.418+0000] {task_command.py:416} INFO - Running <TaskInstance: Scheduler_Traffict_Accident.Transform_Data scheduled__2025-05-22T16:00:00+00:00 [running]> on host 1f18d06af689
[2025-05-22T16:15:10.503+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Hisham' AIRFLOW_CTX_DAG_ID='Scheduler_Traffict_Accident' AIRFLOW_CTX_TASK_ID='Transform_Data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-22T16:00:00+00:00'
[2025-05-22T16:15:10.505+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-22T16:15:10.506+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sudo -u *** python /opt/***/scripts/Transform_Data.py']
[2025-05-22T16:15:10.517+0000] {subprocess.py:86} INFO - Output:
[2025-05-22T16:15:12.207+0000] {subprocess.py:93} INFO - WARNING: An illegal reflective access operation has occurred
[2025-05-22T16:15:12.208+0000] {subprocess.py:93} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2025-05-22T16:15:12.209+0000] {subprocess.py:93} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2025-05-22T16:15:12.209+0000] {subprocess.py:93} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2025-05-22T16:15:12.210+0000] {subprocess.py:93} INFO - WARNING: All illegal access operations will be denied in a future release
[2025-05-22T16:15:12.405+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-05-22T16:15:12.503+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-05-22T16:15:12.504+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-05-22T16:15:12.508+0000] {subprocess.py:93} INFO - org.postgresql#postgresql added as a dependency
[2025-05-22T16:15:12.510+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-3648a36b-ec83-419b-8684-23a258697276;1.0
[2025-05-22T16:15:12.510+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-22T16:15:12.617+0000] {subprocess.py:93} INFO - 	found org.postgresql#postgresql;42.6.0 in central
[2025-05-22T16:15:12.637+0000] {subprocess.py:93} INFO - 	found org.checkerframework#checker-qual;3.31.0 in central
[2025-05-22T16:15:12.649+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 137ms :: artifacts dl 3ms
[2025-05-22T16:15:12.650+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-05-22T16:15:12.650+0000] {subprocess.py:93} INFO - 	org.checkerframework#checker-qual;3.31.0 from central in [default]
[2025-05-22T16:15:12.651+0000] {subprocess.py:93} INFO - 	org.postgresql#postgresql;42.6.0 from central in [default]
[2025-05-22T16:15:12.651+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T16:15:12.652+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-05-22T16:15:12.653+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-05-22T16:15:12.653+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T16:15:12.654+0000] {subprocess.py:93} INFO - 	|      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
[2025-05-22T16:15:12.654+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T16:15:12.655+0000] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-3648a36b-ec83-419b-8684-23a258697276
[2025-05-22T16:15:12.655+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-22T16:15:12.660+0000] {subprocess.py:93} INFO - 	0 artifacts copied, 2 already retrieved (0kB/7ms)
[2025-05-22T16:15:12.872+0000] {subprocess.py:93} INFO - 25/05/22 16:15:12 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-22T16:15:13.134+0000] {subprocess.py:93} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2025-05-22T16:15:13.135+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2025-05-22T16:15:13.136+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-05-22T16:15:16.477+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2025-05-22T16:15:16.493+0000] {process_utils.py:131} INFO - Sending 15 to group 3777. PIDs of all processes in the group: [3778, 3779, 3799, 3777]
[2025-05-22T16:15:16.495+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 3777
[2025-05-22T16:15:16.498+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-22T16:15:16.499+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-05-22T16:15:16.505+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3779, status='terminated', started='16:15:09') (3779) terminated with exit code None
[2025-05-22T16:15:16.521+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 201, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-05-22T16:15:16.535+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Scheduler_Traffict_Accident, task_id=Transform_Data, execution_date=20250522T160000, start_date=20250522T161510, end_date=20250522T161516
[2025-05-22T16:15:16.559+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 15 for task Transform_Data (Task received SIGTERM signal; 3777)
[2025-05-22T16:15:16.601+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3777, status='terminated', exitcode=1, started='16:15:09') (3777) terminated with exit code 1
[2025-05-22T16:15:16.856+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3778, status='terminated', started='16:15:09') (3778) terminated with exit code None
[2025-05-22T16:15:16.990+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3799, status='terminated', started='16:15:10') (3799) terminated with exit code None
[2025-05-22T16:15:16.991+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 143
[2025-05-22T16:15:17.024+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
