[2025-05-22T15:20:59.193+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Scheduler_Traffict_Accident.Load_Data manual__2025-05-22T15:17:26.089500+00:00 [queued]>
[2025-05-22T15:20:59.212+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Scheduler_Traffict_Accident.Load_Data manual__2025-05-22T15:17:26.089500+00:00 [queued]>
[2025-05-22T15:20:59.213+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-22T15:20:59.240+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): Load_Data> on 2025-05-22 15:17:26.089500+00:00
[2025-05-22T15:20:59.250+0000] {standard_task_runner.py:57} INFO - Started process 1044 to run task
[2025-05-22T15:20:59.255+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Scheduler_Traffict_Accident', 'Load_Data', 'manual__2025-05-22T15:17:26.089500+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/Scheduler_Traffict_Accident.py', '--cfg-path', '/tmp/tmpcaj7hhq4']
[2025-05-22T15:20:59.259+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask Load_Data
[2025-05-22T15:20:59.327+0000] {task_command.py:416} INFO - Running <TaskInstance: Scheduler_Traffict_Accident.Load_Data manual__2025-05-22T15:17:26.089500+00:00 [running]> on host 68da71f009b0
[2025-05-22T15:20:59.419+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Hisham' AIRFLOW_CTX_DAG_ID='Scheduler_Traffict_Accident' AIRFLOW_CTX_TASK_ID='Load_Data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T15:17:26.089500+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-22T15:17:26.089500+00:00'
[2025-05-22T15:20:59.421+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-22T15:20:59.422+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sudo -u *** python /opt/***/scripts/Load_Data.py']
[2025-05-22T15:20:59.435+0000] {subprocess.py:86} INFO - Output:
[2025-05-22T15:21:01.429+0000] {subprocess.py:93} INFO - WARNING: An illegal reflective access operation has occurred
[2025-05-22T15:21:01.430+0000] {subprocess.py:93} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2025-05-22T15:21:01.431+0000] {subprocess.py:93} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2025-05-22T15:21:01.431+0000] {subprocess.py:93} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2025-05-22T15:21:01.432+0000] {subprocess.py:93} INFO - WARNING: All illegal access operations will be denied in a future release
[2025-05-22T15:21:01.640+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-05-22T15:21:01.750+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-05-22T15:21:01.751+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-05-22T15:21:01.756+0000] {subprocess.py:93} INFO - org.postgresql#postgresql added as a dependency
[2025-05-22T15:21:01.757+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-5f735c8f-2c43-4bfa-9867-4ce68fb0e4f3;1.0
[2025-05-22T15:21:01.758+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-22T15:21:01.868+0000] {subprocess.py:93} INFO - 	found org.postgresql#postgresql;42.6.0 in central
[2025-05-22T15:21:01.892+0000] {subprocess.py:93} INFO - 	found org.checkerframework#checker-qual;3.31.0 in central
[2025-05-22T15:21:01.908+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 144ms :: artifacts dl 7ms
[2025-05-22T15:21:01.910+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-05-22T15:21:01.911+0000] {subprocess.py:93} INFO - 	org.checkerframework#checker-qual;3.31.0 from central in [default]
[2025-05-22T15:21:01.912+0000] {subprocess.py:93} INFO - 	org.postgresql#postgresql;42.6.0 from central in [default]
[2025-05-22T15:21:01.912+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T15:21:01.913+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-05-22T15:21:01.914+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-05-22T15:21:01.914+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T15:21:01.915+0000] {subprocess.py:93} INFO - 	|      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
[2025-05-22T15:21:01.916+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T15:21:01.916+0000] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-5f735c8f-2c43-4bfa-9867-4ce68fb0e4f3
[2025-05-22T15:21:01.917+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-22T15:21:01.923+0000] {subprocess.py:93} INFO - 	0 artifacts copied, 2 already retrieved (0kB/9ms)
[2025-05-22T15:21:02.150+0000] {subprocess.py:93} INFO - 25/05/22 15:21:02 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-22T15:21:02.434+0000] {subprocess.py:93} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2025-05-22T15:21:02.434+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2025-05-22T15:21:02.435+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-05-22T15:21:11.939+0000] {subprocess.py:93} INFO - [Stage 5:=====>                                                    (1 + 9) / 10]                                                                                Traceback (most recent call last):
[2025-05-22T15:21:11.941+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/Load_Data.py", line 21, in <module>
[2025-05-22T15:21:11.950+0000] {subprocess.py:93} INFO -     data_date.write.jdbc(url=postgres_url, table="date", mode="append", properties=postgres_properties)
[2025-05-22T15:21:11.952+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/sql/readwriter.py", line 1445, in jdbc
[2025-05-22T15:21:11.953+0000] {subprocess.py:93} INFO -     self.mode(mode)._jwrite.jdbc(url, table, jprop)
[2025-05-22T15:21:11.953+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/py4j/java_gateway.py", line 1304, in __call__
[2025-05-22T15:21:11.955+0000] {subprocess.py:93} INFO -     return_value = get_return_value(
[2025-05-22T15:21:11.956+0000] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^
[2025-05-22T15:21:11.958+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/sql/utils.py", line 117, in deco
[2025-05-22T15:21:11.960+0000] {subprocess.py:93} INFO -     raise converted from None
[2025-05-22T15:21:11.961+0000] {subprocess.py:93} INFO - pyspark.sql.utils.AnalysisException: Column "date" not found in schema Some(StructType(StructField(crash_date,DateType,false), StructField(crash_year,IntegerType,true), StructField(crash_month,IntegerType,true), StructField(crash_week,IntegerType,true), StructField(crash_day_of_week,IntegerType,true)))
[2025-05-22T15:21:12.517+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-22T15:21:12.532+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-22T15:21:12.538+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Scheduler_Traffict_Accident, task_id=Load_Data, execution_date=20250522T151726, start_date=20250522T152059, end_date=20250522T152112
[2025-05-22T15:21:12.558+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task Load_Data (Bash command failed. The command returned a non-zero exit code 1.; 1044)
[2025-05-22T15:21:12.573+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-22T15:21:12.592+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
