[2025-05-22T15:33:58.968+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Scheduler_Traffict_Accident.Load_Data manual__2025-05-22T15:17:26.089500+00:00 [queued]>
[2025-05-22T15:33:58.981+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Scheduler_Traffict_Accident.Load_Data manual__2025-05-22T15:17:26.089500+00:00 [queued]>
[2025-05-22T15:33:58.982+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 5
[2025-05-22T15:33:58.998+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): Load_Data> on 2025-05-22 15:17:26.089500+00:00
[2025-05-22T15:33:59.004+0000] {standard_task_runner.py:57} INFO - Started process 3735 to run task
[2025-05-22T15:33:59.008+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Scheduler_Traffict_Accident', 'Load_Data', 'manual__2025-05-22T15:17:26.089500+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/Scheduler_Traffict_Accident.py', '--cfg-path', '/tmp/tmptwv5n47g']
[2025-05-22T15:33:59.013+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask Load_Data
[2025-05-22T15:33:59.079+0000] {task_command.py:416} INFO - Running <TaskInstance: Scheduler_Traffict_Accident.Load_Data manual__2025-05-22T15:17:26.089500+00:00 [running]> on host 68da71f009b0
[2025-05-22T15:33:59.185+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Hisham' AIRFLOW_CTX_DAG_ID='Scheduler_Traffict_Accident' AIRFLOW_CTX_TASK_ID='Load_Data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T15:17:26.089500+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-22T15:17:26.089500+00:00'
[2025-05-22T15:33:59.187+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-22T15:33:59.188+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sudo -u *** python /opt/***/scripts/Load_Data.py']
[2025-05-22T15:33:59.200+0000] {subprocess.py:86} INFO - Output:
[2025-05-22T15:34:01.162+0000] {subprocess.py:93} INFO - WARNING: An illegal reflective access operation has occurred
[2025-05-22T15:34:01.163+0000] {subprocess.py:93} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2025-05-22T15:34:01.164+0000] {subprocess.py:93} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2025-05-22T15:34:01.164+0000] {subprocess.py:93} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2025-05-22T15:34:01.165+0000] {subprocess.py:93} INFO - WARNING: All illegal access operations will be denied in a future release
[2025-05-22T15:34:01.322+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-05-22T15:34:01.404+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-05-22T15:34:01.406+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-05-22T15:34:01.409+0000] {subprocess.py:93} INFO - org.postgresql#postgresql added as a dependency
[2025-05-22T15:34:01.410+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-0011878f-11d9-4322-9860-07a4c97fbd89;1.0
[2025-05-22T15:34:01.411+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-22T15:34:01.512+0000] {subprocess.py:93} INFO - 	found org.postgresql#postgresql;42.6.0 in central
[2025-05-22T15:34:01.530+0000] {subprocess.py:93} INFO - 	found org.checkerframework#checker-qual;3.31.0 in central
[2025-05-22T15:34:01.547+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 130ms :: artifacts dl 7ms
[2025-05-22T15:34:01.548+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-05-22T15:34:01.549+0000] {subprocess.py:93} INFO - 	org.checkerframework#checker-qual;3.31.0 from central in [default]
[2025-05-22T15:34:01.549+0000] {subprocess.py:93} INFO - 	org.postgresql#postgresql;42.6.0 from central in [default]
[2025-05-22T15:34:01.550+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T15:34:01.551+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-05-22T15:34:01.551+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-05-22T15:34:01.552+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T15:34:01.553+0000] {subprocess.py:93} INFO - 	|      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
[2025-05-22T15:34:01.553+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T15:34:01.554+0000] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-0011878f-11d9-4322-9860-07a4c97fbd89
[2025-05-22T15:34:01.554+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-22T15:34:01.556+0000] {subprocess.py:93} INFO - 	0 artifacts copied, 2 already retrieved (0kB/5ms)
[2025-05-22T15:34:01.738+0000] {subprocess.py:93} INFO - 25/05/22 15:34:01 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-22T15:34:02.010+0000] {subprocess.py:93} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2025-05-22T15:34:02.011+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2025-05-22T15:34:02.011+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-05-22T15:34:11.893+0000] {subprocess.py:93} INFO - [Stage 6:>                                                          (0 + 1) / 1]25/05/22 15:34:11 ERROR Executor: Exception in task 0.0 in stage 6.0 (TID 15)
[2025-05-22T15:34:11.894+0000] {subprocess.py:93} INFO - java.sql.BatchUpdateException: Batch entry 0 INSERT INTO date ("date","year","month","day_of_week","week") VALUES ('2013-03-01 +00'::date,2013,3,6,1) was aborted: ERROR: duplicate key value violates unique constraint "date_pkey"
[2025-05-22T15:34:11.896+0000] {subprocess.py:93} INFO -   Detail: Key (date)=(2013-03-01) already exists.  Call getNextException to see other errors in the batch.
[2025-05-22T15:34:11.896+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
[2025-05-22T15:34:11.898+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2402)
[2025-05-22T15:34:11.899+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2134)
[2025-05-22T15:34:11.900+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1491)
[2025-05-22T15:34:11.901+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1516)
[2025-05-22T15:34:11.901+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:560)
[2025-05-22T15:34:11.902+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:896)
[2025-05-22T15:34:11.903+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
[2025-05-22T15:34:11.905+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1685)
[2025-05-22T15:34:11.906+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:687)
[2025-05-22T15:34:11.908+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:856)
[2025-05-22T15:34:11.909+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:854)
[2025-05-22T15:34:11.910+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
[2025-05-22T15:34:11.911+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
[2025-05-22T15:34:11.911+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
[2025-05-22T15:34:11.912+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2025-05-22T15:34:11.912+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2025-05-22T15:34:11.913+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2025-05-22T15:34:11.914+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2025-05-22T15:34:11.915+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2025-05-22T15:34:11.916+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-05-22T15:34:11.916+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-05-22T15:34:11.917+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-22T15:34:11.918+0000] {subprocess.py:93} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "date_pkey"
[2025-05-22T15:34:11.919+0000] {subprocess.py:93} INFO -   Detail: Key (date)=(2013-03-01) already exists.
[2025-05-22T15:34:11.920+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
[2025-05-22T15:34:11.920+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
[2025-05-22T15:34:11.921+0000] {subprocess.py:93} INFO - 	... 21 more
[2025-05-22T15:34:11.947+0000] {subprocess.py:93} INFO - 25/05/22 15:34:11 WARN TaskSetManager: Lost task 0.0 in stage 6.0 (TID 15) (68da71f009b0 executor driver): java.sql.BatchUpdateException: Batch entry 0 INSERT INTO date ("date","year","month","day_of_week","week") VALUES ('2013-03-01 +00'::date,2013,3,6,1) was aborted: ERROR: duplicate key value violates unique constraint "date_pkey"
[2025-05-22T15:34:11.948+0000] {subprocess.py:93} INFO -   Detail: Key (date)=(2013-03-01) already exists.  Call getNextException to see other errors in the batch.
[2025-05-22T15:34:11.949+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
[2025-05-22T15:34:11.949+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2402)
[2025-05-22T15:34:11.950+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2134)
[2025-05-22T15:34:11.951+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1491)
[2025-05-22T15:34:11.952+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1516)
[2025-05-22T15:34:11.953+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:560)
[2025-05-22T15:34:11.954+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:896)
[2025-05-22T15:34:11.955+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
[2025-05-22T15:34:11.956+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1685)
[2025-05-22T15:34:11.957+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:687)
[2025-05-22T15:34:11.959+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:856)
[2025-05-22T15:34:11.959+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:854)
[2025-05-22T15:34:11.960+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
[2025-05-22T15:34:11.961+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
[2025-05-22T15:34:11.961+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
[2025-05-22T15:34:11.962+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2025-05-22T15:34:11.962+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2025-05-22T15:34:11.962+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2025-05-22T15:34:11.963+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2025-05-22T15:34:11.963+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2025-05-22T15:34:11.964+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-05-22T15:34:11.965+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-05-22T15:34:11.965+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-22T15:34:11.966+0000] {subprocess.py:93} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "date_pkey"
[2025-05-22T15:34:11.966+0000] {subprocess.py:93} INFO -   Detail: Key (date)=(2013-03-01) already exists.
[2025-05-22T15:34:11.967+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
[2025-05-22T15:34:11.967+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
[2025-05-22T15:34:11.968+0000] {subprocess.py:93} INFO - 	... 21 more
[2025-05-22T15:34:11.968+0000] {subprocess.py:93} INFO - 
[2025-05-22T15:34:11.969+0000] {subprocess.py:93} INFO - 25/05/22 15:34:11 ERROR TaskSetManager: Task 0 in stage 6.0 failed 1 times; aborting job
[2025-05-22T15:34:12.063+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-22T15:34:12.064+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/Load_Data.py", line 25, in <module>
[2025-05-22T15:34:12.068+0000] {subprocess.py:93} INFO -     data_date.write.jdbc(url=postgres_url, table="date", mode="append", properties=postgres_properties)
[2025-05-22T15:34:12.069+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/sql/readwriter.py", line 1445, in jdbc
[2025-05-22T15:34:12.069+0000] {subprocess.py:93} INFO -     self.mode(mode)._jwrite.jdbc(url, table, jprop)
[2025-05-22T15:34:12.071+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/py4j/java_gateway.py", line 1304, in __call__
[2025-05-22T15:34:12.072+0000] {subprocess.py:93} INFO -     return_value = get_return_value(
[2025-05-22T15:34:12.073+0000] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^
[2025-05-22T15:34:12.073+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/sql/utils.py", line 111, in deco
[2025-05-22T15:34:12.074+0000] {subprocess.py:93} INFO -     return f(*a, **kw)
[2025-05-22T15:34:12.075+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^
[2025-05-22T15:34:12.075+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/py4j/protocol.py", line 326, in get_return_value
[2025-05-22T15:34:12.076+0000] {subprocess.py:93} INFO -     raise Py4JJavaError(
[2025-05-22T15:34:12.123+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o56.jdbc.
[2025-05-22T15:34:12.124+0000] {subprocess.py:93} INFO - : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 6.0 failed 1 times, most recent failure: Lost task 0.0 in stage 6.0 (TID 15) (68da71f009b0 executor driver): java.sql.BatchUpdateException: Batch entry 0 INSERT INTO date ("date","year","month","day_of_week","week") VALUES ('2013-03-01 +00'::date,2013,3,6,1) was aborted: ERROR: duplicate key value violates unique constraint "date_pkey"
[2025-05-22T15:34:12.125+0000] {subprocess.py:93} INFO -   Detail: Key (date)=(2013-03-01) already exists.  Call getNextException to see other errors in the batch.
[2025-05-22T15:34:12.125+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
[2025-05-22T15:34:12.126+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2402)
[2025-05-22T15:34:12.127+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2134)
[2025-05-22T15:34:12.129+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1491)
[2025-05-22T15:34:12.129+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1516)
[2025-05-22T15:34:12.130+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:560)
[2025-05-22T15:34:12.131+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:896)
[2025-05-22T15:34:12.131+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
[2025-05-22T15:34:12.132+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1685)
[2025-05-22T15:34:12.133+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:687)
[2025-05-22T15:34:12.134+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:856)
[2025-05-22T15:34:12.134+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:854)
[2025-05-22T15:34:12.135+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
[2025-05-22T15:34:12.136+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
[2025-05-22T15:34:12.137+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
[2025-05-22T15:34:12.138+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2025-05-22T15:34:12.138+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2025-05-22T15:34:12.139+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2025-05-22T15:34:12.139+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2025-05-22T15:34:12.140+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2025-05-22T15:34:12.141+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-05-22T15:34:12.141+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-05-22T15:34:12.142+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-22T15:34:12.143+0000] {subprocess.py:93} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "date_pkey"
[2025-05-22T15:34:12.143+0000] {subprocess.py:93} INFO -   Detail: Key (date)=(2013-03-01) already exists.
[2025-05-22T15:34:12.144+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
[2025-05-22T15:34:12.144+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
[2025-05-22T15:34:12.145+0000] {subprocess.py:93} INFO - 	... 21 more
[2025-05-22T15:34:12.146+0000] {subprocess.py:93} INFO - 
[2025-05-22T15:34:12.147+0000] {subprocess.py:93} INFO - Driver stacktrace:
[2025-05-22T15:34:12.148+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2258)
[2025-05-22T15:34:12.148+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2207)
[2025-05-22T15:34:12.149+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2206)
[2025-05-22T15:34:12.150+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-05-22T15:34:12.151+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-05-22T15:34:12.152+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-05-22T15:34:12.153+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2206)
[2025-05-22T15:34:12.154+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1079)
[2025-05-22T15:34:12.154+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1079)
[2025-05-22T15:34:12.155+0000] {subprocess.py:93} INFO - 	at scala.Option.foreach(Option.scala:407)
[2025-05-22T15:34:12.156+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1079)
[2025-05-22T15:34:12.158+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2445)
[2025-05-22T15:34:12.159+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2387)
[2025-05-22T15:34:12.161+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2376)
[2025-05-22T15:34:12.162+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2025-05-22T15:34:12.162+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:868)
[2025-05-22T15:34:12.164+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2196)
[2025-05-22T15:34:12.164+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2217)
[2025-05-22T15:34:12.166+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2236)
[2025-05-22T15:34:12.167+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2261)
[2025-05-22T15:34:12.168+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$1(RDD.scala:1020)
[2025-05-22T15:34:12.169+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2025-05-22T15:34:12.170+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
[2025-05-22T15:34:12.171+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
[2025-05-22T15:34:12.172+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:1018)
[2025-05-22T15:34:12.173+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.saveTable(JdbcUtils.scala:854)
[2025-05-22T15:34:12.174+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:68)
[2025-05-22T15:34:12.175+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
[2025-05-22T15:34:12.176+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
[2025-05-22T15:34:12.177+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
[2025-05-22T15:34:12.178+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:90)
[2025-05-22T15:34:12.179+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
[2025-05-22T15:34:12.179+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
[2025-05-22T15:34:12.180+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2025-05-22T15:34:12.180+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
[2025-05-22T15:34:12.181+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
[2025-05-22T15:34:12.181+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:132)
[2025-05-22T15:34:12.182+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:131)
[2025-05-22T15:34:12.183+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:989)
[2025-05-22T15:34:12.184+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
[2025-05-22T15:34:12.184+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
[2025-05-22T15:34:12.185+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
[2025-05-22T15:34:12.186+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
[2025-05-22T15:34:12.187+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
[2025-05-22T15:34:12.187+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:989)
[2025-05-22T15:34:12.188+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:438)
[2025-05-22T15:34:12.189+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:415)
[2025-05-22T15:34:12.189+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:301)
[2025-05-22T15:34:12.190+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.jdbc(DataFrameWriter.scala:817)
[2025-05-22T15:34:12.190+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-22T15:34:12.191+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-22T15:34:12.192+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-22T15:34:12.192+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-22T15:34:12.193+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-22T15:34:12.194+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-22T15:34:12.194+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-22T15:34:12.194+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-22T15:34:12.195+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-22T15:34:12.195+0000] {subprocess.py:93} INFO - 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
[2025-05-22T15:34:12.197+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-22T15:34:12.197+0000] {subprocess.py:93} INFO - Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO date ("date","year","month","day_of_week","week") VALUES ('2013-03-01 +00'::date,2013,3,6,1) was aborted: ERROR: duplicate key value violates unique constraint "date_pkey"
[2025-05-22T15:34:12.197+0000] {subprocess.py:93} INFO -   Detail: Key (date)=(2013-03-01) already exists.  Call getNextException to see other errors in the batch.
[2025-05-22T15:34:12.198+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
[2025-05-22T15:34:12.199+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2402)
[2025-05-22T15:34:12.199+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2134)
[2025-05-22T15:34:12.200+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1491)
[2025-05-22T15:34:12.200+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1516)
[2025-05-22T15:34:12.201+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:560)
[2025-05-22T15:34:12.202+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:896)
[2025-05-22T15:34:12.202+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
[2025-05-22T15:34:12.204+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1685)
[2025-05-22T15:34:12.205+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:687)
[2025-05-22T15:34:12.206+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:856)
[2025-05-22T15:34:12.206+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:854)
[2025-05-22T15:34:12.207+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
[2025-05-22T15:34:12.208+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
[2025-05-22T15:34:12.208+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
[2025-05-22T15:34:12.209+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2025-05-22T15:34:12.210+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2025-05-22T15:34:12.210+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2025-05-22T15:34:12.210+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2025-05-22T15:34:12.211+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2025-05-22T15:34:12.211+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-05-22T15:34:12.212+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-05-22T15:34:12.212+0000] {subprocess.py:93} INFO - 	... 1 more
[2025-05-22T15:34:12.213+0000] {subprocess.py:93} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "date_pkey"
[2025-05-22T15:34:12.213+0000] {subprocess.py:93} INFO -   Detail: Key (date)=(2013-03-01) already exists.
[2025-05-22T15:34:12.214+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
[2025-05-22T15:34:12.214+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
[2025-05-22T15:34:12.215+0000] {subprocess.py:93} INFO - 	... 21 more
[2025-05-22T15:34:12.215+0000] {subprocess.py:93} INFO - 
[2025-05-22T15:34:12.609+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-22T15:34:12.622+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-22T15:34:12.628+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Scheduler_Traffict_Accident, task_id=Load_Data, execution_date=20250522T151726, start_date=20250522T153358, end_date=20250522T153412
[2025-05-22T15:34:12.645+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task Load_Data (Bash command failed. The command returned a non-zero exit code 1.; 3735)
[2025-05-22T15:34:12.692+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-22T15:34:12.708+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
