[2025-05-20T15:00:28.394+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Scheduler_Traffict_Accident.Load_Data scheduled__2025-05-20T14:45:00+00:00 [queued]>
[2025-05-20T15:00:28.416+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Scheduler_Traffict_Accident.Load_Data scheduled__2025-05-20T14:45:00+00:00 [queued]>
[2025-05-20T15:00:28.417+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-05-20T15:00:28.419+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2025-05-20T15:00:28.419+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-05-20T15:00:28.435+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): Load_Data> on 2025-05-20 14:45:00+00:00
[2025-05-20T15:00:28.441+0000] {standard_task_runner.py:52} INFO - Started process 1953 to run task
[2025-05-20T15:00:28.445+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Scheduler_Traffict_Accident', 'Load_Data', 'scheduled__2025-05-20T14:45:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/Scheduler_Traffict_Accident.py', '--cfg-path', '/tmp/tmprsi0tpb3', '--error-file', '/tmp/tmpls6m_3an']
[2025-05-20T15:00:28.447+0000] {standard_task_runner.py:80} INFO - Job 8: Subtask Load_Data
[2025-05-20T15:00:28.530+0000] {task_command.py:371} INFO - Running <TaskInstance: Scheduler_Traffict_Accident.Load_Data scheduled__2025-05-20T14:45:00+00:00 [running]> on host 240265f9b255
[2025-05-20T15:00:28.601+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Hisham
AIRFLOW_CTX_DAG_ID=Scheduler_Traffict_Accident
AIRFLOW_CTX_TASK_ID=Load_Data
AIRFLOW_CTX_EXECUTION_DATE=2025-05-20T14:45:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-05-20T14:45:00+00:00
[2025-05-20T15:00:28.603+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-05-20T15:00:28.604+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'sudo -u *** python /opt/***/scripts/Load_Data.py']
[2025-05-20T15:00:28.614+0000] {subprocess.py:85} INFO - Output:
[2025-05-20T15:00:30.039+0000] {subprocess.py:92} INFO - WARNING: An illegal reflective access operation has occurred
[2025-05-20T15:00:30.040+0000] {subprocess.py:92} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.7/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2025-05-20T15:00:30.040+0000] {subprocess.py:92} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2025-05-20T15:00:30.041+0000] {subprocess.py:92} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2025-05-20T15:00:30.041+0000] {subprocess.py:92} INFO - WARNING: All illegal access operations will be denied in a future release
[2025-05-20T15:00:30.192+0000] {subprocess.py:92} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.7/site-packages/pyspark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-05-20T15:00:30.265+0000] {subprocess.py:92} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-05-20T15:00:30.266+0000] {subprocess.py:92} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-05-20T15:00:30.269+0000] {subprocess.py:92} INFO - org.postgresql#postgresql added as a dependency
[2025-05-20T15:00:30.270+0000] {subprocess.py:92} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-0b9d90fd-9961-4970-8bf2-6037f39debcf;1.0
[2025-05-20T15:00:30.271+0000] {subprocess.py:92} INFO - 	confs: [default]
[2025-05-20T15:00:30.364+0000] {subprocess.py:92} INFO - 	found org.postgresql#postgresql;42.6.0 in central
[2025-05-20T15:00:30.387+0000] {subprocess.py:92} INFO - 	found org.checkerframework#checker-qual;3.31.0 in central
[2025-05-20T15:00:30.400+0000] {subprocess.py:92} INFO - :: resolution report :: resolve 125ms :: artifacts dl 5ms
[2025-05-20T15:00:30.401+0000] {subprocess.py:92} INFO - 	:: modules in use:
[2025-05-20T15:00:30.402+0000] {subprocess.py:92} INFO - 	org.checkerframework#checker-qual;3.31.0 from central in [default]
[2025-05-20T15:00:30.403+0000] {subprocess.py:92} INFO - 	org.postgresql#postgresql;42.6.0 from central in [default]
[2025-05-20T15:00:30.404+0000] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-05-20T15:00:30.404+0000] {subprocess.py:92} INFO - 	|                  |            modules            ||   artifacts   |
[2025-05-20T15:00:30.405+0000] {subprocess.py:92} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-05-20T15:00:30.405+0000] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-05-20T15:00:30.406+0000] {subprocess.py:92} INFO - 	|      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
[2025-05-20T15:00:30.406+0000] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-05-20T15:00:30.407+0000] {subprocess.py:92} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-0b9d90fd-9961-4970-8bf2-6037f39debcf
[2025-05-20T15:00:30.407+0000] {subprocess.py:92} INFO - 	confs: [default]
[2025-05-20T15:00:30.408+0000] {subprocess.py:92} INFO - 	0 artifacts copied, 2 already retrieved (0kB/4ms)
[2025-05-20T15:00:30.567+0000] {subprocess.py:92} INFO - 25/05/20 15:00:30 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-20T15:00:30.780+0000] {subprocess.py:92} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2025-05-20T15:00:30.781+0000] {subprocess.py:92} INFO - Setting default log level to "WARN".
[2025-05-20T15:00:30.781+0000] {subprocess.py:92} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-05-20T15:00:38.681+0000] {subprocess.py:92} INFO - [Stage 6:>                                                          (0 + 1) / 1]25/05/20 15:00:38 ERROR Executor: Exception in task 0.0 in stage 6.0 (TID 15)
[2025-05-20T15:00:38.682+0000] {subprocess.py:92} INFO - java.sql.BatchUpdateException: Batch entry 0 INSERT INTO date ("crash_date","crash_year","crash_month","crash_day_of_week","crash_week") VALUES ('2013-03-01',2013,3,6,1) was aborted: ERROR: column "crash_date" is of type date but expression is of type character varying
[2025-05-20T15:00:38.683+0000] {subprocess.py:92} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-20T15:00:38.684+0000] {subprocess.py:92} INFO -   Position: 101  Call getNextException to see other errors in the batch.
[2025-05-20T15:00:38.685+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
[2025-05-20T15:00:38.685+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:880)
[2025-05-20T15:00:38.686+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
[2025-05-20T15:00:38.686+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1685)
[2025-05-20T15:00:38.687+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:687)
[2025-05-20T15:00:38.687+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:856)
[2025-05-20T15:00:38.688+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:854)
[2025-05-20T15:00:38.689+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
[2025-05-20T15:00:38.690+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
[2025-05-20T15:00:38.691+0000] {subprocess.py:92} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
[2025-05-20T15:00:38.692+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2025-05-20T15:00:38.693+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2025-05-20T15:00:38.695+0000] {subprocess.py:92} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2025-05-20T15:00:38.696+0000] {subprocess.py:92} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2025-05-20T15:00:38.696+0000] {subprocess.py:92} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2025-05-20T15:00:38.697+0000] {subprocess.py:92} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-05-20T15:00:38.697+0000] {subprocess.py:92} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-05-20T15:00:38.698+0000] {subprocess.py:92} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-20T15:00:38.698+0000] {subprocess.py:92} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: column "crash_date" is of type date but expression is of type character varying
[2025-05-20T15:00:38.699+0000] {subprocess.py:92} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-20T15:00:38.699+0000] {subprocess.py:92} INFO -   Position: 101
[2025-05-20T15:00:38.700+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
[2025-05-20T15:00:38.700+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
[2025-05-20T15:00:38.701+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
[2025-05-20T15:00:38.701+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:327)
[2025-05-20T15:00:38.702+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:877)
[2025-05-20T15:00:38.702+0000] {subprocess.py:92} INFO - 	... 16 more
[2025-05-20T15:00:38.720+0000] {subprocess.py:92} INFO - 25/05/20 15:00:38 WARN TaskSetManager: Lost task 0.0 in stage 6.0 (TID 15) (240265f9b255 executor driver): java.sql.BatchUpdateException: Batch entry 0 INSERT INTO date ("crash_date","crash_year","crash_month","crash_day_of_week","crash_week") VALUES ('2013-03-01',2013,3,6,1) was aborted: ERROR: column "crash_date" is of type date but expression is of type character varying
[2025-05-20T15:00:38.721+0000] {subprocess.py:92} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-20T15:00:38.721+0000] {subprocess.py:92} INFO -   Position: 101  Call getNextException to see other errors in the batch.
[2025-05-20T15:00:38.722+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
[2025-05-20T15:00:38.722+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:880)
[2025-05-20T15:00:38.723+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
[2025-05-20T15:00:38.723+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1685)
[2025-05-20T15:00:38.724+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:687)
[2025-05-20T15:00:38.724+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:856)
[2025-05-20T15:00:38.725+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:854)
[2025-05-20T15:00:38.725+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
[2025-05-20T15:00:38.726+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
[2025-05-20T15:00:38.726+0000] {subprocess.py:92} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
[2025-05-20T15:00:38.727+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2025-05-20T15:00:38.727+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2025-05-20T15:00:38.728+0000] {subprocess.py:92} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2025-05-20T15:00:38.728+0000] {subprocess.py:92} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2025-05-20T15:00:38.729+0000] {subprocess.py:92} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2025-05-20T15:00:38.730+0000] {subprocess.py:92} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-05-20T15:00:38.730+0000] {subprocess.py:92} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-05-20T15:00:38.731+0000] {subprocess.py:92} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-20T15:00:38.731+0000] {subprocess.py:92} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: column "crash_date" is of type date but expression is of type character varying
[2025-05-20T15:00:38.731+0000] {subprocess.py:92} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-20T15:00:38.732+0000] {subprocess.py:92} INFO -   Position: 101
[2025-05-20T15:00:38.732+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
[2025-05-20T15:00:38.733+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
[2025-05-20T15:00:38.733+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
[2025-05-20T15:00:38.734+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:327)
[2025-05-20T15:00:38.734+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:877)
[2025-05-20T15:00:38.735+0000] {subprocess.py:92} INFO - 	... 16 more
[2025-05-20T15:00:38.735+0000] {subprocess.py:92} INFO - 
[2025-05-20T15:00:38.736+0000] {subprocess.py:92} INFO - 25/05/20 15:00:38 ERROR TaskSetManager: Task 0 in stage 6.0 failed 1 times; aborting job
[2025-05-20T15:00:38.877+0000] {subprocess.py:92} INFO - Traceback (most recent call last):
[2025-05-20T15:00:38.878+0000] {subprocess.py:92} INFO -   File "/opt/***/scripts/Load_Data.py", line 21, in <module>
[2025-05-20T15:00:38.878+0000] {subprocess.py:92} INFO -     data_date.write.jdbc(url=postgres_url, table="date", mode="append", properties=postgres_properties)
[2025-05-20T15:00:38.879+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/sql/readwriter.py", line 1445, in jdbc
[2025-05-20T15:00:38.879+0000] {subprocess.py:92} INFO -     self.mode(mode)._jwrite.jdbc(url, table, jprop)
[2025-05-20T15:00:38.880+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1305, in __call__
[2025-05-20T15:00:38.881+0000] {subprocess.py:92} INFO -     answer, self.gateway_client, self.target_id, self.name)
[2025-05-20T15:00:38.881+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/sql/utils.py", line 111, in deco
[2025-05-20T15:00:38.882+0000] {subprocess.py:92} INFO -     return f(*a, **kw)
[2025-05-20T15:00:38.883+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
[2025-05-20T15:00:38.883+0000] {subprocess.py:92} INFO -     format(target_id, ".", name), value)
[2025-05-20T15:00:38.884+0000] {subprocess.py:92} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o53.jdbc.
[2025-05-20T15:00:38.885+0000] {subprocess.py:92} INFO - : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 6.0 failed 1 times, most recent failure: Lost task 0.0 in stage 6.0 (TID 15) (240265f9b255 executor driver): java.sql.BatchUpdateException: Batch entry 0 INSERT INTO date ("crash_date","crash_year","crash_month","crash_day_of_week","crash_week") VALUES ('2013-03-01',2013,3,6,1) was aborted: ERROR: column "crash_date" is of type date but expression is of type character varying
[2025-05-20T15:00:38.886+0000] {subprocess.py:92} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-20T15:00:38.886+0000] {subprocess.py:92} INFO -   Position: 101  Call getNextException to see other errors in the batch.
[2025-05-20T15:00:38.887+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
[2025-05-20T15:00:38.888+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:880)
[2025-05-20T15:00:38.888+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
[2025-05-20T15:00:38.889+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1685)
[2025-05-20T15:00:38.890+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:687)
[2025-05-20T15:00:38.890+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:856)
[2025-05-20T15:00:38.890+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:854)
[2025-05-20T15:00:38.891+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
[2025-05-20T15:00:38.891+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
[2025-05-20T15:00:38.892+0000] {subprocess.py:92} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
[2025-05-20T15:00:38.892+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2025-05-20T15:00:38.893+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2025-05-20T15:00:38.894+0000] {subprocess.py:92} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2025-05-20T15:00:38.894+0000] {subprocess.py:92} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2025-05-20T15:00:38.895+0000] {subprocess.py:92} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2025-05-20T15:00:38.895+0000] {subprocess.py:92} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-05-20T15:00:38.896+0000] {subprocess.py:92} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-05-20T15:00:38.897+0000] {subprocess.py:92} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-20T15:00:38.898+0000] {subprocess.py:92} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: column "crash_date" is of type date but expression is of type character varying
[2025-05-20T15:00:38.898+0000] {subprocess.py:92} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-20T15:00:38.899+0000] {subprocess.py:92} INFO -   Position: 101
[2025-05-20T15:00:38.900+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
[2025-05-20T15:00:38.900+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
[2025-05-20T15:00:38.901+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
[2025-05-20T15:00:38.901+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:327)
[2025-05-20T15:00:38.902+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:877)
[2025-05-20T15:00:38.903+0000] {subprocess.py:92} INFO - 	... 16 more
[2025-05-20T15:00:38.903+0000] {subprocess.py:92} INFO - 
[2025-05-20T15:00:38.904+0000] {subprocess.py:92} INFO - Driver stacktrace:
[2025-05-20T15:00:38.905+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2258)
[2025-05-20T15:00:38.905+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2207)
[2025-05-20T15:00:38.906+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2206)
[2025-05-20T15:00:38.906+0000] {subprocess.py:92} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-05-20T15:00:38.907+0000] {subprocess.py:92} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-05-20T15:00:38.908+0000] {subprocess.py:92} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-05-20T15:00:38.908+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2206)
[2025-05-20T15:00:38.910+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1079)
[2025-05-20T15:00:38.911+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1079)
[2025-05-20T15:00:38.912+0000] {subprocess.py:92} INFO - 	at scala.Option.foreach(Option.scala:407)
[2025-05-20T15:00:38.912+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1079)
[2025-05-20T15:00:38.913+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2445)
[2025-05-20T15:00:38.914+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2387)
[2025-05-20T15:00:38.915+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2376)
[2025-05-20T15:00:38.916+0000] {subprocess.py:92} INFO - 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2025-05-20T15:00:38.917+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:868)
[2025-05-20T15:00:38.918+0000] {subprocess.py:92} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2196)
[2025-05-20T15:00:38.919+0000] {subprocess.py:92} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2217)
[2025-05-20T15:00:38.919+0000] {subprocess.py:92} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2236)
[2025-05-20T15:00:38.921+0000] {subprocess.py:92} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2261)
[2025-05-20T15:00:38.922+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$1(RDD.scala:1020)
[2025-05-20T15:00:38.923+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2025-05-20T15:00:38.923+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
[2025-05-20T15:00:38.925+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
[2025-05-20T15:00:38.926+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:1018)
[2025-05-20T15:00:38.927+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.saveTable(JdbcUtils.scala:854)
[2025-05-20T15:00:38.928+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:68)
[2025-05-20T15:00:38.929+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
[2025-05-20T15:00:38.929+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
[2025-05-20T15:00:38.930+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
[2025-05-20T15:00:38.930+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:90)
[2025-05-20T15:00:38.931+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
[2025-05-20T15:00:38.932+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
[2025-05-20T15:00:38.932+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2025-05-20T15:00:38.933+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
[2025-05-20T15:00:38.934+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
[2025-05-20T15:00:38.935+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:132)
[2025-05-20T15:00:38.935+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:131)
[2025-05-20T15:00:38.936+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:989)
[2025-05-20T15:00:38.937+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
[2025-05-20T15:00:38.937+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
[2025-05-20T15:00:38.938+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
[2025-05-20T15:00:38.939+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
[2025-05-20T15:00:38.939+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
[2025-05-20T15:00:38.940+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:989)
[2025-05-20T15:00:38.940+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:438)
[2025-05-20T15:00:38.941+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:415)
[2025-05-20T15:00:38.942+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:301)
[2025-05-20T15:00:38.942+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.DataFrameWriter.jdbc(DataFrameWriter.scala:817)
[2025-05-20T15:00:38.943+0000] {subprocess.py:92} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-20T15:00:38.943+0000] {subprocess.py:92} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-20T15:00:38.944+0000] {subprocess.py:92} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-20T15:00:38.945+0000] {subprocess.py:92} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-20T15:00:38.945+0000] {subprocess.py:92} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-20T15:00:38.946+0000] {subprocess.py:92} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-20T15:00:38.947+0000] {subprocess.py:92} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-20T15:00:38.947+0000] {subprocess.py:92} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-20T15:00:38.948+0000] {subprocess.py:92} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-20T15:00:38.949+0000] {subprocess.py:92} INFO - 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
[2025-05-20T15:00:38.949+0000] {subprocess.py:92} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-20T15:00:38.950+0000] {subprocess.py:92} INFO - Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO date ("crash_date","crash_year","crash_month","crash_day_of_week","crash_week") VALUES ('2013-03-01',2013,3,6,1) was aborted: ERROR: column "crash_date" is of type date but expression is of type character varying
[2025-05-20T15:00:38.951+0000] {subprocess.py:92} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-20T15:00:38.951+0000] {subprocess.py:92} INFO -   Position: 101  Call getNextException to see other errors in the batch.
[2025-05-20T15:00:38.952+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
[2025-05-20T15:00:38.952+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:880)
[2025-05-20T15:00:38.953+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
[2025-05-20T15:00:38.954+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1685)
[2025-05-20T15:00:38.955+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:687)
[2025-05-20T15:00:38.956+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:856)
[2025-05-20T15:00:38.956+0000] {subprocess.py:92} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:854)
[2025-05-20T15:00:38.957+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
[2025-05-20T15:00:38.958+0000] {subprocess.py:92} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
[2025-05-20T15:00:38.958+0000] {subprocess.py:92} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
[2025-05-20T15:00:38.959+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2025-05-20T15:00:38.959+0000] {subprocess.py:92} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2025-05-20T15:00:38.960+0000] {subprocess.py:92} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2025-05-20T15:00:38.960+0000] {subprocess.py:92} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2025-05-20T15:00:38.961+0000] {subprocess.py:92} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2025-05-20T15:00:38.961+0000] {subprocess.py:92} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-05-20T15:00:38.962+0000] {subprocess.py:92} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-05-20T15:00:38.962+0000] {subprocess.py:92} INFO - 	... 1 more
[2025-05-20T15:00:38.963+0000] {subprocess.py:92} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: column "crash_date" is of type date but expression is of type character varying
[2025-05-20T15:00:38.963+0000] {subprocess.py:92} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-20T15:00:38.964+0000] {subprocess.py:92} INFO -   Position: 101
[2025-05-20T15:00:38.965+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
[2025-05-20T15:00:38.965+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
[2025-05-20T15:00:38.966+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
[2025-05-20T15:00:38.967+0000] {subprocess.py:92} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:327)
[2025-05-20T15:00:38.968+0000] {subprocess.py:92} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:877)
[2025-05-20T15:00:38.968+0000] {subprocess.py:92} INFO - 	... 16 more
[2025-05-20T15:00:38.969+0000] {subprocess.py:92} INFO - 
[2025-05-20T15:00:39.348+0000] {subprocess.py:96} INFO - Command exited with return code 1
[2025-05-20T15:00:39.369+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-20T15:00:39.377+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=Scheduler_Traffict_Accident, task_id=Load_Data, execution_date=20250520T144500, start_date=20250520T150028, end_date=20250520T150039
[2025-05-20T15:00:39.393+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 8 for task Load_Data (Bash command failed. The command returned a non-zero exit code 1.; 1953)
[2025-05-20T15:00:39.400+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-05-20T15:00:39.433+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
